services:
  - type: web
    name: fileshare
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_ID
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: VALID_TOKENS
        value: "abc123,x

